changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 'New Features'
      labels:
        - 'feat'
        - 'feature'
    - title: 'Bug Fixes'
      labels:
        - 'fix'
        - 'bug'
    - title: 'Documentation'
      labels:
        - 'docs'
        - 'documentation'
    - title: 'Maintenance'
      labels:
        - 'chore'
        - 'build'
        - 'ci'
        - 'refactor'
        - 'style'
